/**
 * PDF export utilities using browser print API.
 * Creates a clean printable view and triggers print/save-as-PDF.
 */

import type { Scholarship, SavedScholarship, Application } from "./api";
import { toast } from "@/hooks/use-toast";

function openPrintWindow(html: string, title: string) {
  const win = window.open("", "_blank");
  if (!win) {
    toast({ title: "Please allow popups to export PDF", variant: "destructive" });
    return;
  }
  win.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #1a1a2e; }
        h1 { font-size: 24px; margin-bottom: 8px; color: #1a56db; }
        h2 { font-size: 18px; margin: 24px 0 12px; color: #1a56db; }
        h3 { font-size: 15px; margin-bottom: 4px; }
        .subtitle { color: #666; font-size: 14px; margin-bottom: 24px; }
        .card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin-bottom: 16px; page-break-inside: avoid; }
        .card-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 8px; }
        .badge { background: #eff6ff; color: #1a56db; padding: 2px 10px; border-radius: 9999px; font-size: 12px; font-weight: 500; }
        .amount { font-weight: 700; font-size: 16px; }
        .meta { color: #666; font-size: 13px; margin-top: 4px; }
        .tag { display: inline-block; background: #f3f4f6; padding: 2px 8px; border-radius: 4px; font-size: 12px; margin: 2px 4px 2px 0; }
        .section-list { list-style: disc; padding-left: 20px; margin-top: 8px; }
        .section-list li { font-size: 13px; margin-bottom: 4px; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #e5e7eb; font-size: 13px; }
        th { background: #f9fafb; font-weight: 600; }
        .footer { margin-top: 40px; text-align: center; color: #999; font-size: 12px; border-top: 1px solid #e5e7eb; padding-top: 16px; }
        @media print { body { padding: 20px; } .no-print { display: none; } }
      </style>
    </head>
    <body>
      ${html}
      <div class="footer">
        Generated by ScholarHub &bull; ${new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" })}
      </div>
      <script>window.onload = function() { window.print(); }</script>
    </body>
    </html>
  `);
  win.document.close();
}

// ── Export single scholarship detail ────────────────────────────

export function exportScholarshipPDF(s: Scholarship) {
  const eligibility = s.eligibility_criteria?.length
    ? `<h2>Eligibility Criteria</h2><ul class="section-list">${s.eligibility_criteria.map((c) => `<li>${c}</li>`).join("")}</ul>`
    : "";

  const docs = s.documents_required?.length
    ? `<h2>Required Documents</h2><ul class="section-list">${s.documents_required.map((d) => `<li>${d}</li>`).join("")}</ul>`
    : "";

  const html = `
    <h1>${s.name}</h1>
    <p class="subtitle">${s.provider}</p>
    <div class="card">
      <div style="display: flex; gap: 24px; flex-wrap: wrap;">
        <div><strong>Amount:</strong> ₹${Number(s.amount).toLocaleString("en-IN")}</div>
        <div><strong>Deadline:</strong> ${s.deadline ? new Date(s.deadline).toLocaleDateString("en-IN") : "N/A"}</div>
        <div><strong>Type:</strong> <span class="badge">${s.type}</span></div>
        ${s.education_level ? `<div><strong>Education:</strong> ${s.education_level}</div>` : ""}
        ${s.category ? `<div><strong>Category:</strong> ${s.category}</div>` : ""}
        ${s.state ? `<div><strong>State:</strong> ${s.state}</div>` : ""}
      </div>
    </div>
    ${s.description ? `<h2>Description</h2><p style="font-size: 14px; line-height: 1.6;">${s.description}</p>` : ""}
    ${eligibility}
    ${docs}
    ${s.official_url ? `<h2>Official Link</h2><p style="font-size: 14px;">${s.official_url}</p>` : ""}
  `;

  openPrintWindow(html, `${s.name} - ScholarHub`);
}

// ── Export saved scholarships list ──────────────────────────────

export function exportSavedListPDF(scholarships: (Scholarship | SavedScholarship)[]) {
  const rows = scholarships
    .map(
      (s) => `
    <tr>
      <td><strong>${s.name}</strong><br/><span style="color:#666">${s.provider}</span></td>
      <td>₹${Number(s.amount).toLocaleString("en-IN")}</td>
      <td>${s.deadline ? new Date(s.deadline).toLocaleDateString("en-IN") : "N/A"}</td>
      <td><span class="badge">${s.type}</span></td>
    </tr>`
    )
    .join("");

  const html = `
    <h1>My Saved Scholarships</h1>
    <p class="subtitle">${scholarships.length} scholarships saved</p>
    <table>
      <thead><tr><th>Scholarship</th><th>Amount</th><th>Deadline</th><th>Type</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
  `;

  openPrintWindow(html, "Saved Scholarships - ScholarHub");
}

// ── Export applications list ────────────────────────────────────

export function exportApplicationsPDF(applications: Application[]) {
  const rows = applications
    .map(
      (a) => `
    <tr>
      <td><strong>${a.scholarship_name}</strong><br/><span style="color:#666">${a.provider}</span></td>
      <td><span class="badge">${a.status.replace("_", " ")}</span></td>
      <td>₹${Number(a.amount).toLocaleString("en-IN")}</td>
      <td>${a.deadline ? new Date(a.deadline).toLocaleDateString("en-IN") : "N/A"}</td>
    </tr>`
    )
    .join("");

  const html = `
    <h1>My Scholarship Applications</h1>
    <p class="subtitle">${applications.length} applications tracked</p>
    <table>
      <thead><tr><th>Scholarship</th><th>Status</th><th>Amount</th><th>Deadline</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
  `;

  openPrintWindow(html, "Applications - ScholarHub");
}
